import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

export type CicloMcpInstallClient = "claude" | "codex";

export interface CicloMcpServerConfig {
  readonly command: string;
  readonly args: readonly string[];
  readonly env: Record<string, string>;
}

export interface CicloMcpInstallOptions {
  readonly projectRoot?: string;
  readonly clients?: readonly CicloMcpInstallClient[];
  readonly serverName?: string;
  readonly command?: string;
  readonly claudeChannel?: boolean;
  readonly dryRun?: boolean;
}

export interface CicloMcpInstallTargetResult {
  readonly client: CicloMcpInstallClient;
  readonly path: string;
  readonly changed: boolean;
  readonly dryRun: boolean;
}

export interface CicloMcpInstallResult {
  readonly installed: boolean;
  readonly projectRoot: string;
  readonly serverName: string;
  readonly server: CicloMcpServerConfig;
  readonly claudeChannel?: CicloClaudeChannelInstall;
  readonly targets: readonly CicloMcpInstallTargetResult[];
  readonly nextSteps: readonly string[];
}

export interface CicloClaudeChannelInstall {
  readonly enabled: boolean;
  readonly selector: string;
  readonly launchArgs: readonly string[];
}

function assertServerName(name: string): void {
  if (!/^[A-Za-z0-9_-]+$/u.test(name)) {
    throw new Error("--server-name may only contain letters, numbers, underscore, or dash");
  }
}

function uniqueClients(clients: readonly CicloMcpInstallClient[]): readonly CicloMcpInstallClient[] {
  return [...new Set(clients)];
}

function serverConfig(projectRoot: string, command: string, claudeChannel: boolean): CicloMcpServerConfig {
  return {
    command,
    args: ["mcp", "stdio"],
    env: {
      CICLO_PROJECT_ROOT: projectRoot,
      ...(claudeChannel ? { CICLO_CLAUDE_CHANNEL: "true" } : {})
    }
  };
}

function readJsonFile(path: string): unknown {
  if (!existsSync(path)) return {};
  const raw = readFileSync(path, "utf8").trim();
  if (raw.length === 0) return {};
  return JSON.parse(raw) as unknown;
}

function asJsonObject(value: unknown, path: string): Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(`${path} must contain a JSON object`);
  }
  return value as Record<string, unknown>;
}

function writeIfChanged(path: string, content: string, dryRun: boolean): boolean {
  const previous = existsSync(path) ? readFileSync(path, "utf8") : undefined;
  const changed = previous !== content;
  if (changed && !dryRun) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
  }
  return changed;
}

function installClaude(projectRoot: string, serverName: string, config: CicloMcpServerConfig, dryRun: boolean): CicloMcpInstallTargetResult {
  const path = join(projectRoot, ".mcp.json");
  const root = asJsonObject(readJsonFile(path), path);
  const mcpServers = asJsonObject(root.mcpServers ?? {}, `${path}:mcpServers`);
  root.mcpServers = {
    ...mcpServers,
    [serverName]: config
  };

  const changed = writeIfChanged(path, `${JSON.stringify(root, null, 2)}\n`, dryRun);
  return { client: "claude", path, changed, dryRun };
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlStringList(values: readonly string[]): string {
  return `[${values.map(tomlString).join(", ")}]`;
}

function stripCodexServerBlock(input: string, serverName: string): string {
  const lines = input.split(/\r?\n/u);
  const kept: string[] = [];
  let dropping = false;

  for (const line of lines) {
    const table = line.match(/^\s*\[([^\]]+)\]\s*$/u)?.[1];
    if (table !== undefined) {
      dropping = table === `mcp_servers.${serverName}` || table.startsWith(`mcp_servers.${serverName}.`);
    }
    if (!dropping) kept.push(line);
  }

  return kept.join("\n").replace(/[ \t]+\n/gu, "\n").replace(/\n{3,}$/u, "\n\n").trimEnd();
}

function codexTomlBlock(serverName: string, config: CicloMcpServerConfig): string {
  const envEntries = Object.entries(config.env)
    .map(([key, value]) => `${key} = ${tomlString(value)}`)
    .join("\n");
  return [
    "# Ciclo MCP server; generated by `ciclo mcp install`.",
    `[mcp_servers.${serverName}]`,
    `command = ${tomlString(config.command)}`,
    `args = ${tomlStringList(config.args)}`,
    "",
    `[mcp_servers.${serverName}.env]`,
    envEntries
  ].join("\n");
}

function installCodex(projectRoot: string, serverName: string, config: CicloMcpServerConfig, dryRun: boolean): CicloMcpInstallTargetResult {
  const path = join(projectRoot, ".codex", "config.toml");
  const previous = existsSync(path) ? readFileSync(path, "utf8") : "";
  const stripped = stripCodexServerBlock(previous, serverName);
  const next = `${stripped.length === 0 ? "" : `${stripped}\n\n`}${codexTomlBlock(serverName, config)}\n`;
  const changed = writeIfChanged(path, next, dryRun);
  return { client: "codex", path, changed, dryRun };
}

export function installCicloMcp(options: CicloMcpInstallOptions = {}): CicloMcpInstallResult {
  const projectRoot = resolve(options.projectRoot ?? process.cwd());
  const serverName = options.serverName ?? "ciclo";
  assertServerName(serverName);

  const clients = uniqueClients(options.clients ?? ["claude"]);
  const command = options.command ?? "ciclo";
  const dryRun = options.dryRun ?? false;
  const claudeChannelEnabled = options.claudeChannel === true;
  if (claudeChannelEnabled && !clients.includes("claude")) {
    throw new Error("--claude-channel requires --client claude or --client all");
  }
  const config = serverConfig(projectRoot, command, claudeChannelEnabled);
  const claudeChannel: CicloClaudeChannelInstall | undefined = claudeChannelEnabled
    ? {
        enabled: true,
        selector: `server:${serverName}`,
        launchArgs: ["--dangerously-load-development-channels", `server:${serverName}`]
      }
    : undefined;

  const targets = clients.map((client) => {
    if (client === "claude") return installClaude(projectRoot, serverName, config, dryRun);
    return installCodex(projectRoot, serverName, config, dryRun);
  });

  return {
    installed: targets.some((target) => target.changed) && !dryRun,
    projectRoot,
    serverName,
    server: config,
    ...(claudeChannel === undefined ? {} : { claudeChannel }),
    targets,
    nextSteps: [
      "Start Claude or Codex in the project after restarting the client if it does not hot-reload MCP config.",
      ...(claudeChannel === undefined
        ? []
        : [`Start Claude Code with ${claudeChannel.launchArgs.join(" ")} to enable the Ciclo MCP channel preview.`]),
      "Ask the session to use Ciclo MCP for status, work claims, operator questions, worker launches, and closeout evidence.",
      "Use ciclo mcp install --client codex or --client all when the same project should expose Ciclo to Codex too."
    ]
  };
}
